name: Espressif IoT Development Framework (ESP-IDF)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Espressif IoT Development Framework (ESP-IDF)
        uses: espressif/esp-idf-ci-action@v1.2.0
        with:
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: . # optional, default is root
          # Version of ESP-IDF docker image to use
          esp_idf_version: release-v5.3 # optional, default is latest
          # ESP32 variant to build for
          target: esp32c6 # optional, default is esp32
          # Command to run inside the docker container (default: builds the project)
          command: idf.py fullclean && idf.py build # optional, default is idf.py build
                
